### PR TITLE
fix: langfuse filter pipeline cost tracking

### LINKED ISSUE #267: langfuse_filter_pipeline.py 'str' object has no attribute 'get'
langfuse_filter_pipeline.py is error

'str' object has no attribute 'get'

image
image
image

### PR DESCRIPTION
**Pull request by marcklingen**
Fixes #267 (`langfuse_filter_pipeline.py 'str' object has no attribute 'get'`)

### CODE REVIEW

**Comment by marcklingen** [comment]
@tjbck I fixed the issue that I introduced in #263, tested it end to end on openai, streaming openai and various ollama models

**Comment by tjbck** [comment]
LGTM, Thanks!

**Comment by marcklingen** [comment]
thanks for the quick review
